#!/usr/bin/env python3
"""Generate Rust MDCT twiddle table for 48k/960 from C static table."""
from pathlib import Path
import re

SRC = Path('opus-c/celt/static_modes_float.h')
OUT = Path('src/celt/mdct_twiddles_48000_960.rs')

text = SRC.read_text()
match = re.search(r'mdct_twiddles960\[1800\]\s*=\s*\{(.*?)\};', text, re.S)
if not match:
    raise SystemExit('mdct_twiddles960 not found in static_modes_float.h')
body = match.group(1)
nums = re.findall(r'[-+]?(?:\d+\.\d+|\d+\.?)(?:e[-+]?\d+)?', body, re.I)
if len(nums) != 1800:
    raise SystemExit(f'expected 1800 numbers, got {len(nums)}')

out = []
out.append('// Source: opus-c/celt/static_modes_float.h (mdct_twiddles960).')
out.append('// Generated by scripts/gen_mdct_twiddles_48000_960.py (from the C table).')
out.append('// Copied verbatim to preserve bit-exact parity with the C table.')
out.append('#![allow(clippy::approx_constant, clippy::excessive_precision)]')
out.append('')
out.append('use super::types::KissTwiddleScalar;')
out.append('')
out.append('pub(crate) const MDCT_TWIDDLES_960: [KissTwiddleScalar; 1800] = [')
line = '    '
for i, num in enumerate(nums):
    lit = re.sub('E', 'e', num)
    if 'e' not in lit and '.' not in lit:
        lit += '.0'
    lit += '_f32'
    if len(line) + len(lit) + 2 > 100:
        out.append(line.rstrip())
        line = '    '
    line += lit + ', '
    if (i + 1) % 8 == 0:
        out.append(line.rstrip())
        line = '    '
if line.strip():
    out.append(line.rstrip())
out.append('];')

OUT.write_text('\n'.join(out) + '\n')
print(f'Wrote {OUT}')
