#!/usr/bin/env python3
from pathlib import Path
import re

SRC = Path("opus-c/celt/static_modes_float.h")
OUT = Path("src/celt/fft_bitrev_480.rs")

text = SRC.read_text(encoding="utf-8")
match = re.search(r"fft_bitrev480\[480\]\s*=\s*\{(.*?)\};", text, re.S)
if not match:
    raise SystemExit("fft_bitrev480 table not found")
body = match.group(1)
nums = re.findall(r"-?\d+", body)
if len(nums) != 480:
    raise SystemExit(f"expected 480 entries, got {len(nums)}")

lines = []
lines.append("// Source: opus-c/celt/static_modes_float.h (fft_bitrev480).")
lines.append("// Generated by scripts/gen_fft_bitrev_480.py (from the C table).")
lines.append("// Copied verbatim to preserve bit-exact parity with the C table.")
lines.append("use super::types::OpusInt16;")
lines.append("")
lines.append("pub(crate) const FFT_BITREV_480: [OpusInt16; 480] = [")
line = "    "
for i, num in enumerate(nums):
    lit = f"{num}"
    if len(line) + len(lit) + 2 > 100:
        lines.append(line.rstrip())
        line = "    "
    line += lit + ", "
    if (i + 1) % 16 == 0:
        lines.append(line.rstrip())
        line = "    "
if line.strip():
    lines.append(line.rstrip())
lines.append("];\n")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUT}")
